---
- name: Clean previous Kismet installation and generated files.
  include: clean.yml
  when: ({{ kismet_rpi_build_clean }})

- name: Build Kismet from src tarball.
  include: build.yml
  when: ({{ kismet_rpi_build_build }})

- name: Publish and copy 'deb' from RPi to 'host' and HTTPd 'localmirror'.
  include: publish.yml
  when: ({{ kismet_rpi_build_publish }})
